language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"

env:
    - DJANGO="1.3.7"
    - DJANGO="1.4.16"
    - DJANGO="1.5.11"
    - DJANGO="1.6.8"
    - DJANGO="1.7.1"
    - DJANGO="1.8.0"

install:
    - pip install Django==$DJANGO --use-mirrors
    - pip install coverage==3.6
    - pip install python-coveralls==2.4.0
    - export PYTHONPATH=.

before_script: coverage erase

script: coverage run --source=vanilla manage.py test

after_success: coverage report; coveralls

matrix:
    exclude:
        - python: "2.6"
          env: DJANGO="1.8.0"
        - python: "2.6"
          env: DJANGO="1.7.1"
        - python: "3.2"
          env: DJANGO="1.4.16"
        - python: "3.2"
          env: DJANGO="1.3.7"
        - python: "3.3"
          env: DJANGO="1.4.16"
        - python: "3.3"
          env: DJANGO="1.3.7"
        - python: "3.4"
          env: DJANGO="1.6.8"
        - python: "3.4"
          env: DJANGO="1.5.11"
        - python: "3.4"
          env: DJANGO="1.4.16"
        - python: "3.4"
          env: DJANGO="1.3.7"
