language: python

python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"

env:
    - DJANGO="1.9.6"
    - DJANGO="1.8.13"

install:
    - pip install Django==$DJANGO
    - pip install coverage==3.6
    - pip install python-coveralls==2.4.0
    - export PYTHONPATH=.

before_script: coverage erase

script: coverage run --source=vanilla manage.py test

after_success: coverage report; coveralls

matrix:
    exclude:
        - python: "3.2"
          env: DJANGO="1.9.6"
        - python: "3.3"
          env: DJANGO="1.9.6"

