language: python

python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

env:
    - DJANGO=1.11.27
    - DJANGO=2.0.13
    - DJANGO=2.1.15
    - DJANGO=2.2.9
    - DJANGO=3.0.2
    - DJANGO=3.1.1

install:
    - pip install Django==$DJANGO
    - pip install coverage python-coveralls
    - export PYTHONPATH=.

before_script: coverage erase

script: coverage run --source=vanilla manage.py test

after_success: coverage report; coveralls

matrix:
    include:
        - python: "3.9-dev"
          env: DJANGO=3.1.1
    exclude:
        - python: "3.5"
          env: DJANGO=3.0.2
        - python: "3.5"
          env: DJANGO=3.1.1
        - python: "3.8"
          env: DJANGO=1.11.27
