language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

env:
    - DJANGO=1.11.27
    - DJANGO=2.0.13
    - DJANGO=2.1.15
    - DJANGO=2.2.9
    - DJANGO=3.0.2

install:
    - pip install Django==$DJANGO
    - pip install coverage
    - pip install python-coveralls==2.9.1 'PyYAML<5.3'
    - export PYTHONPATH=.

before_script: coverage erase

script: coverage run --source=vanilla manage.py test

after_success: coverage report; coveralls

matrix:
    exclude:
        - python: "2.7"
          env: DJANGO=2.0.13
        - python: "2.7"
          env: DJANGO=2.1.15
        - python: "2.7"
          env: DJANGO=2.2.9
        - python: "2.7"
          env: DJANGO=3.0.2
        - python: "3.4"
          env: DJANGO=2.1.15
        - python: "3.4"
          env: DJANGO=2.2.9
        - python: "3.4"
          env: DJANGO=3.0.2
        - python: "3.5"
          env: DJANGO=3.0.2
        - python: "3.8"
          env: DJANGO=1.11.27
